### PR TITLE
Add forcerange  approximation with max isometric force

### PR DESCRIPTION
**Pull request by SashaMalysheva**
For [OpenSim Rl](https://github.com/stanfordnmbl/osim-rl/tree/610b95cf0c4484f1acecd31187736b0113dcfb73) usage add forcerange.

### CODE REVIEW

**Comment by gpzhaome** [comment]
I think the max force should be higher than the max isometric force (e.g., during eccentric muscle contraction). Otherwise this could have an similar effect as clipping the force-velocity curve. I'm not sure how much this would influence the simulation for OpenSim RI usage.

**Comment by aikkala** [comment]
Thanks @SashaMalysheva. We recently pushed a commit that sets "max_isometric_force" (from opensim) as the "force" muscle parameter (in mujoco). @gpzhaome do you mean that the max in "forcerange" should be higher than "max_isometric_force", or that the "force" muscle parameter should be higher than "max_isometric_force"?

**Comment by gpzhaome** [comment]
@aikkala Sorry for the confusion. I mean the max in "forcerange" should be higher than "max_isometric_force". The "force" muscle parameter in Mujoco is defined as the peak active force at zero velocity, which is equivalent to the max isometric force.

**Comment by aikkala** [comment]
Thanks @gpzhaome for confirming this. Closing this PR for now, but if @SashaMalysheva or someone else has an idea how the forcerange should be estimated I'd be happy to hear it.

**Pull request closed without merging**
